apiVersion: v1
kind: Service
metadata:
  name: ai-lab
spec:
  type: {{ .Values.service.type }}
  selector:
    app: ai-lab
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
